const excelor = require('./excel/index')
const { data: project } = { "success": true, "data": { "id": 111, "title": "asdasd", "slug": "asdasd", "provider_id": 1, "note": null, "client": "{}", "provider": { "id": 1, "name": "FelipeCorp", "created_at": null, "updated_at": null, "deleted_at": null }, "created_at": "2019-08-19T16:29:20.000000Z", "updated_at": "2019-08-19T16:29:33.000000Z", "version": { "project_id": 111, "version_reference": 3, "rooms": [
  { "name": "Travaux G\u00e9n\u00e9raux", "slug": "Travaux-Generaux", "steps": [{ "id": 7, "tags": [], "unit": "m2", "price": "1.60", "category": "painting", "quantity": "3", "room_type": "general", "unit_price": "1.20", "description": "Ipsam odio sunt laudantium nulla natus et." }], "roomType": "general", "stepCompleted": [true, true, null] },
  { "name": "Salle de bains", "slug": "Travaux-Generaux", "steps": [{ "id": 7, "tags": [], "unit": "m2", "price": "1.60", "category": "painting", "quantity": "3", "room_type": "general", "unit_price": "1.20", "description": "Ipsam odio sunt laudantium nulla natus et." }], "roomType": "general", "stepCompleted": [true, true, null] },
], "locked": 1, "price": "4.80", "note": null, "rooms_count": 1, "xls_path": null, "pdf_path": "quotes\/quote-asdasd-3.xls", "created_at": "2019-08-19T16:35:32.000000Z", "updated_at": "2019-08-19T17:16:37.000000Z" }, "versions": [{ "project_id": 111, "version_reference": 3, "rooms": [{ "name": "Travaux G\u00e9n\u00e9raux", "slug": "Travaux-Generaux", "steps": [{ "id": 7, "tags": [], "unit": "m2", "price": "1.60", "category": "painting", "quantity": "3", "room_type": "general", "unit_price": "1.20", "description": "Ipsam odio sunt laudantium nulla natus et." }], "roomType": "general", "stepCompleted": [true, true, null] }], "locked": 1, "price": "4.80", "note": null, "rooms_count": 1, "xls_path": null, "pdf_path": "quotes\/quote-asdasd-3.xls", "created_at": "2019-08-19T16:35:32.000000Z", "updated_at": "2019-08-19T17:16:37.000000Z" }, { "project_id": 111, "version_reference": 2, "rooms": [{ "name": "Travaux G\u00e9n\u00e9raux", "slug": "Travaux-Generaux", "steps": [{ "id": 7, "tags": [], "unit": "m2", "price": "1.60", "category": "painting", "quantity": "3", "room_type": "general", "unit_price": "1.20", "description": "Ipsam odio sunt laudantium nulla natus et." }], "roomType": "general", "stepCompleted": [true, true, null] }, { "name": "Salle de bains", "slug": "Travaux-Generaux", "steps": [{ "id": 7, "tags": [], "unit": "m2", "price": "1.60", "category": "painting", "quantity": "3", "room_type": "general", "unit_price": "1.20", "description": "Ipsam odio sunt laudantium nulla natus et." }], "roomType": "general", "stepCompleted": [true, true, null] }], "locked": 1, "price": "4.80", "note": null, "rooms_count": 1, "xls_path": null, "pdf_path": null, "created_at": "2019-08-19T16:30:37.000000Z", "updated_at": "2019-08-19T16:30:37.000000Z" }, { "project_id": 111, "version_reference": 1, "rooms": [{ "name": "Travaux G\u00e9n\u00e9raux", "slug": "Travaux-Generaux", "steps": [{ "id": 7, "tags": [], "unit": "m2", "price": "1.60", "category": "painting", "quantity": "3", "room_type": "general", "unit_price": "1.20", "description": "Ipsam odio sunt laudantium nulla natus et." }], "roomType": "general", "stepCompleted": [true, true, null] }], "locked": 1, "price": "4.80", "note": null, "rooms_count": 1, "xls_path": null, "pdf_path": null, "created_at": "2019-08-19T16:29:33.000000Z", "updated_at": "2019-08-19T16:29:33.000000Z" }] }, "message": "Project retrieved successfully." };
async function test(){
  await new excelor(project).createDocument();
}

test()